---
abstract: 'An implementation of the Amazon Glacier RESTful API.'
author:
  - 'Tim Nordenfur <tim@gurka.se>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Amazon-Glacier
no_index:
  directory:
    - t
    - inc
requires:
  Digest::SHA: 0
  File::Slurp: 0
  JSON::PP: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Net::Amazon::Signature::V4: 0
  Net::Amazon::TreeHash: 0
  Test::More: 0
version: 0.12
